# AIPACK Configuration for Rust Code Evaluation
[options]
model = "llama3.2:3b"

[options.model_aliases]
llama3 = "llama3.2:3b"
codellama = "codellama:7b"
deepseek = "deepseek-coder:latest"
rust-coder = "victornitu/rust-coder:latest"
qwen25-coder = "qwen2.5-coder:latest"
