[package]
name = "data-compactor"
version = "0.1.0"
edition = "2021"
description = "High-performance data compaction library for JSON structures"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
